version: "1.0"
# Este es un archivo de docker-compose.yml para configurar el uso de contenedores de software aplicado a sqlite.

services:
  db: 




  adminer:

    container_name: adminer
    image: adminer:4.8.0
    restart: always
    ports:

      - 8080:8080


  modulo_3:
    # build es el lugar desde donde toma los archivos para generar la imagen.
    build: .
    # Imágen a utilizar:
    image: modulo_3
    # Nombre del container:
    container_name: modulo_3
    # Comportamiento ante fallos y al iniciar el sistema:
    restart: always
    # Carpetas enlazadas:
    volumes:
      # Source code directory:
      - type: bind
        source: .
        target: /opt/back_end
    # Puertos enlazados:
    ports:
        - "8000:8000"
    # Control de consola:
    stdin_open: true
    tty: true
    
    command: python marvel/manage.py runserver 0.0.0.0:8000